### ISSUE TITLE
How to enable the `on-this-page` menu?

### ISSUE THREAD

**Issue by ANovokmet** [svelteness/svelteness#99]
I can't seem to figure it out. My pages just show a blank element where the menu should be.

Relevant code seems to be https://github.com/svelteness/kit-docs/blob/main/packages/kit-docs/src/lib/components/layout/OnThisPage.svelte#L21

**Comment by michael-voit** [comment]
@ANovokmet The moment you have several headlines in the document, the on-this-page sidebar is shown automatically.

If this doesn't work, please share the code of your content file.

**Comment by ANovokmet** [comment]
@michael-voit Thanks, you're right. It is working. Only for headers level 2 and 3 (##, ###), while I had only those of level 1.

**Comment by michael-voit** [comment]
Great!
